/* TinyCC build configuration for CrusadIA (i386, freestanding, in-kernel).
 * Picked up by tinycc/tcc.h via `#include "config.h"` (found through -Itccport). */
#define TCC_VERSION "0.9.28rc"
#define TCC_TARGET_I386 1

/* no dlopen/dlsym; symbols are provided with tcc_add_symbol() */
#define CONFIG_TCC_STATIC 1
/* no signals / backtraces / bounds checker in a kernel */
#define CONFIG_TCC_BACKTRACE 0
#define CONFIG_TCC_BCHECK 0
#define CONFIG_TCC_SEMLOCK 0
/* embed tccdefs.h in the binary (generated by the Makefile: tccport/gen/tccdefs_.h) */
#define CONFIG_TCC_PREDEFS 1

/* virtual paths, served from memory by tccport/tcc_vfs.c */
#define CONFIG_TCCDIR "/tcc"
#define CONFIG_TCC_SYSINCLUDEPATHS "/tcc/include"
#define CONFIG_TCC_LIBPATHS "/tcc/lib"
#define CONFIG_TCC_CRTPREFIX "/tcc/lib"
#define CONFIG_TCC_ELFINTERP "/none"
