/* Host tool (built with the host compiler by the Makefile):
 *   mkembed out.h file1 file2 ...
 * writes a C header embedding every file, addressed by its basename.
 * Same idea as tinycc's own c2str, but for arbitrary text/binary files. */
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: mkembed out.h files...\n"); return 1; }
    FILE *out = fopen(argv[1], "wb");
    if (!out) { perror(argv[1]); return 1; }
    fprintf(out, "/* generated by tccport/mkembed - do not edit */\n");
    fprintf(out, "struct tcc_efile { const char *name; const unsigned char *data; unsigned size; };\n");
    for (int i = 2; i < argc; i++) {
        FILE *in = fopen(argv[i], "rb");
        if (!in) { perror(argv[i]); return 1; }
        fprintf(out, "static const unsigned char tcc_efile_%d[] = {", i - 2);
        int c, n = 0;
        while ((c = fgetc(in)) != EOF) fprintf(out, "%s%d,", (n++ % 24) ? "" : "\n", c);
        fprintf(out, "0};\n");
        fclose(in);
    }
    fprintf(out, "static const struct tcc_efile tcc_efiles[] = {\n");
    for (int i = 2; i < argc; i++) {
        const char *base = strrchr(argv[i], '/');
        base = base ? base + 1 : argv[i];
        fprintf(out, "  { \"%s\", tcc_efile_%d, sizeof(tcc_efile_%d) - 1 },\n", base, i - 2, i - 2);
    }
    fprintf(out, "};\n#define TCC_EFILE_COUNT (sizeof(tcc_efiles) / sizeof(tcc_efiles[0]))\n");
    fclose(out);
    return 0;
}
