/*
 * tcc_vfs.c - file access for TinyCC.
 *
 *  /tcc/include/<name>   -> headers compiled into the kernel (tcc_embedded.h,
 *                           generated by the Makefile with tccport/mkembed)
 *  everything else       -> CrusadIA's own open()/read()/close()/lseek()
 *
 * Returned descriptors:  embedded file i  -> 100 + i
 *                        real fd n        -> n + 3   (never 0, 1, 2)
 */
#include <stddef.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include "tcc_embedded.h"

#define VFD_EMBED_BASE 100
#define VFD_MAX        8
#define VFD_REAL_SHIFT 3
#define INC_PREFIX     "/tcc/include/"

static struct { int used; const unsigned char *data; unsigned size, pos; } vfd[VFD_MAX];

static const struct tcc_efile *find_embedded(const char *path) {
    size_t pl = strlen(INC_PREFIX);
    if (strncmp(path, INC_PREFIX, pl) != 0) return 0;
    const char *name = path + pl;
    for (unsigned i = 0; i < TCC_EFILE_COUNT; i++)
        if (strcmp(tcc_efiles[i].name, name) == 0) return &tcc_efiles[i];
    return 0;
}

int tcc_os_open(const char *path, int flags, ...) {
    if (!(flags & (O_WRONLY | O_RDWR | O_CREAT | O_TRUNC | O_APPEND))) {
        const struct tcc_efile *e = find_embedded(path);
        if (e) {
            for (int i = 0; i < VFD_MAX; i++) {
                if (!vfd[i].used) {
                    vfd[i].used = 1; vfd[i].data = e->data; vfd[i].size = e->size; vfd[i].pos = 0;
                    return VFD_EMBED_BASE + i;
                };
            }
            return -1;
        }
        if (strncmp(path, "/tcc/", 5) == 0) return -1; 
    }
    int fd = open(path, flags);
    return fd < 0 ? -1 : fd + VFD_REAL_SHIFT;
}

FILE *tcc_os_fdopen(int fd, const char *mode) {
    if (fd < VFD_REAL_SHIFT) return 0;
    return fdopen(fd - VFD_REAL_SHIFT, mode);
}

long tcc_os_read(int fd, void *buf, size_t n) {
    if (fd >= VFD_EMBED_BASE) {
        int i = fd - VFD_EMBED_BASE;
        if (i >= VFD_MAX || !vfd[i].used) return -1;
        unsigned left = vfd[i].size - vfd[i].pos;
        if (n > left) n = left;
        memcpy(buf, vfd[i].data + vfd[i].pos, n);
        vfd[i].pos += (unsigned)n;
        return (long)n;
    }
    if (fd < VFD_REAL_SHIFT) return -1;
    return read(fd - VFD_REAL_SHIFT, buf, n);
}

int tcc_os_close(int fd) {
    if (fd >= VFD_EMBED_BASE) {
        int i = fd - VFD_EMBED_BASE;
        if (i >= VFD_MAX || !vfd[i].used) return -1;
        vfd[i].used = 0;
        return 0;
    }
    if (fd < VFD_REAL_SHIFT) return -1;
    return close(fd - VFD_REAL_SHIFT);
}

long tcc_os_lseek(int fd, long off, int whence) {
    if (fd >= VFD_EMBED_BASE) {
        int i = fd - VFD_EMBED_BASE;
        if (i >= VFD_MAX || !vfd[i].used) return -1;
        long base = whence == SEEK_SET ? 0 : whence == SEEK_CUR ? (long)vfd[i].pos : (long)vfd[i].size;
        long t = base + off;
        if (t < 0) return -1;
        vfd[i].pos = (unsigned)t;
        return t;
    }
    if (fd < VFD_REAL_SHIFT) return -1;
    return lseek(fd - VFD_REAL_SHIFT, off, whence);
}
