/*
 * tcc_kernel.c - TinyCC as a kernel service ("in-OS compiler").
 *
 *   source (.c file or string)
 *        |  libtcc: tcc_add_file / tcc_compile_string
 *        v
 *   machine code in heap memory (TCC_OUTPUT_MEMORY, tcc_relocate)
 *        |  the kernel is identity mapped and has no NX, so it is executable
 *        v
 *   main(argc, argv)  -- runs in ring 0, directly calling kernel functions
 *                        that we export with tcc_add_symbol()
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>
#include <time.h>
#include <fcntl.h>
#include <unistd.h>
#include "libtcc.h"
#include "tcc_kernel.h"
#include "klog.h"
#include "vesa.h"
#include "rtc.h"
#include "fs.h"

extern volatile uint32_t system_ticks;   /* idt.c, 1000 Hz PIT tick */

/* ------------------------------------------------ what programs may call */

/* TinyCC runtime helpers from tcc1.c (64-bit math, float<->int64) */
extern char tcc1___ashldi3[], tcc1___ashrdi3[], tcc1___divdi3[], tcc1___fixdfdi[],
            tcc1___fixsfdi[], tcc1___fixunsdfdi[], tcc1___fixunssfdi[], tcc1___fixunsxfdi[],
            tcc1___fixxfdi[], tcc1___floatundidf[], tcc1___floatundisf[], tcc1___floatundixf[],
            tcc1___lshrdi3[], tcc1___moddi3[], tcc1___udivdi3[], tcc1___umoddi3[];

static jmp_buf guest_exit_jb;
static int     guest_exit_code;
static int     guest_running;

static void guest_exit(int code) {
    if (guest_running) {
        guest_exit_code = code;
        longjmp(guest_exit_jb, 1);
    }
    for (;;) __asm__ volatile("hlt");
}
static void guest_abort(void) { guest_exit(134); }

void os_sleep_ms(uint32_t ms) {
    uint32_t target = system_ticks + ms;
    while ((int32_t)(system_ticks - target) < 0) __asm__ volatile("sti; hlt");
}

#define SYM(x)        { #x, (const void *)&x }
#define SYM_AS(n, x)  { n,  (const void *)&x }

static const struct { const char *name; const void *addr; } guest_syms[] = {
    /* --- console / screen (klog.h, vesa.h) --- */
    SYM(klog), SYM(kklog), SYM(klogf), SYM(klog_color),
    SYM(Wwidth), SYM(Hheight), SYM(vesa_putpixel), SYM(vesa_draw_rec),
    SYM(vesa_clear), SYM(vesa_swap),
    /* --- time --- */
    SYM(system_ticks), SYM(os_sleep_ms), SYM(rtc_get_datetime), SYM(time), SYM(localtime),
    /* --- stdio --- */
    SYM(printf), SYM(fprintf), SYM(sprintf), SYM(snprintf), SYM(vsnprintf), SYM(vfprintf),
    SYM(puts), SYM(putchar), SYM(fputs), SYM(fputc), SYM(fflush),
    SYM(fopen), SYM(fclose), SYM(fread), SYM(fwrite), SYM(fseek), SYM(ftell), SYM(feof),
    SYM(remove), SYM(stdin), SYM(stdout), SYM(stderr),
    /* --- fd api --- */
    SYM(open), SYM(read), SYM(write), SYM(lseek), SYM(close), SYM(unlink),
    /* --- stdlib / string --- */
    SYM(malloc), SYM(calloc), SYM(realloc), SYM(free),
    SYM_AS("exit", guest_exit), SYM_AS("abort", guest_abort),
    SYM(abs), SYM(atoi), SYM(strtol), SYM(strtoul), SYM(strtod), SYM(qsort), SYM(bsearch), SYM(itoa),
    SYM(memcpy), SYM(memmove), SYM(memset), SYM(memcmp), SYM(memchr),
    SYM(strlen), SYM(strcmp), SYM(strncmp), SYM(strcasecmp), SYM(strcpy), SYM(strncpy),
    SYM(strcat), SYM(strncat), SYM(strchr), SYM(strrchr), SYM(strstr), SYM(strdup),
    /* --- compiler runtime (code generated by tcc calls these by name) --- */
    SYM_AS("__ashldi3", tcc1___ashldi3),       SYM_AS("__ashrdi3", tcc1___ashrdi3),
    SYM_AS("__divdi3", tcc1___divdi3),         SYM_AS("__moddi3", tcc1___moddi3),
    SYM_AS("__udivdi3", tcc1___udivdi3),       SYM_AS("__umoddi3", tcc1___umoddi3),
    SYM_AS("__lshrdi3", tcc1___lshrdi3),
    SYM_AS("__fixdfdi", tcc1___fixdfdi),       SYM_AS("__fixsfdi", tcc1___fixsfdi),
    SYM_AS("__fixxfdi", tcc1___fixxfdi),       SYM_AS("__fixunsdfdi", tcc1___fixunsdfdi),
    SYM_AS("__fixunssfdi", tcc1___fixunssfdi), SYM_AS("__fixunsxfdi", tcc1___fixunsxfdi),
    SYM_AS("__floatundidf", tcc1___floatundidf), SYM_AS("__floatundisf", tcc1___floatundisf),
    SYM_AS("__floatundixf", tcc1___floatundixf),
};
#define GUEST_SYM_COUNT (sizeof(guest_syms) / sizeof(guest_syms[0]))

/* ------------------------------------------------------ low level helpers */

/* x87 FPU: TinyCC keeps float constants in `long double`. */
static void tcc_os_fpu_init(void) {
#ifndef TCC_HOST_TEST                  /* ring 3 test harness cannot touch CR0 */
    uint32_t cr0;
    __asm__ volatile("mov %%cr0, %0" : "=r"(cr0));
    cr0 &= ~((1u << 2) | (1u << 3));   /* EM, TS off */
    cr0 |=  (1u << 1) | (1u << 5);     /* MP, NE on  */
    __asm__ volatile("mov %0, %%cr0" :: "r"(cr0));
#endif
    __asm__ volatile("fninit");
}

/* int tcc_os_call_on_stack(void *stack_top, int (*fn)(void *), void *arg)
 * Runs fn(arg) on a different stack. The kernel tasks only have 16 KB stacks,
 * TinyCC's parser recursion needs far more. */
int tcc_os_call_on_stack(void *stack_top, int (*fn)(void *), void *arg);
__asm__(
    ".pushsection .text\n"
    ".globl tcc_os_call_on_stack\n"
    "tcc_os_call_on_stack:\n"
    "    pushl %ebp\n"
    "    movl  %esp, %ebp\n"
    "    pushl %ebx\n"
    "    movl  8(%ebp), %eax\n"      /* new stack top          */
    "    movl  12(%ebp), %ecx\n"     /* fn                     */
    "    movl  16(%ebp), %edx\n"     /* arg                    */
    "    movl  %esp, %ebx\n"         /* old esp (callee-saved) */
    "    movl  %eax, %esp\n"
    "    subl  $12, %esp\n"          /* keep 16-byte alignment */
    "    pushl %edx\n"
    "    call  *%ecx\n"
    "    movl  %ebx, %esp\n"
    "    popl  %ebx\n"
    "    popl  %ebp\n"
    "    ret\n"
    ".popsection\n");

/* --------------------------------------------------------- the compiler */

typedef struct {
    const char *name;      /* path (file mode) or display name (string mode) */
    const char *source;    /* NULL = compile the file `name`                 */
    int    argc;
    char **argv;
    int    compiled;       /* out: 1 if the program was built and started   */
    int    exit_code;      /* out                                            */
} run_req_t;

static void tcc_error_cb(void *opaque, const char *msg) {
    (void)opaque;
    klog_color(msg, 0xFF6060);
    klog("\n");
}

static int do_run(void *arg) {
    run_req_t *r = (run_req_t *)arg;
    int (*entry)(int, char **);
    volatile int code = 0;

    TCCState *s = tcc_new();
    if (!s) { kklog("cc: tcc_new() failed (out of memory?)"); return -1; }
    tcc_set_error_func(s, 0, tcc_error_cb);
    tcc_set_options(s, "-nostdlib");                 /* no libtcc1.a / crt files */
    if (tcc_set_output_type(s, TCC_OUTPUT_MEMORY) < 0) goto fail;

    for (unsigned i = 0; i < GUEST_SYM_COUNT; i++)
        tcc_add_symbol(s, guest_syms[i].name, guest_syms[i].addr);

    if ((r->source ? tcc_compile_string(s, r->source) : tcc_add_file(s, r->name)) < 0) goto fail;
    if (tcc_relocate(s) < 0) goto fail;

    entry = (int (*)(int, char **))tcc_get_symbol(s, "main");
    if (!entry) { kklog("cc: no main() function"); goto fail; }

    r->compiled = 1;
    guest_running = 1;
    if (setjmp(guest_exit_jb) == 0) code = entry(r->argc, r->argv);
    else                            code = guest_exit_code;
    guest_running = 0;
    r->exit_code = code;

    tcc_delete(s);
    return 0;
fail:
    tcc_delete(s);
    return -1;
}

typedef struct {
    const char *name;      /* path (file mode) or display name (string mode) */
    const char *source;    /* NULL = compile the file `name`                 */
    const char *out_path;  /* where to write the .o file on the drive        */
    int    ok;             /* out: 1 if the .o file was written              */
} compile_req_t;

static int do_compile_obj(void *arg) {
    compile_req_t *r = (compile_req_t *)arg;

    TCCState *s = tcc_new();
    if (!s) { kklog("cc: tcc_new() failed (out of memory?)"); return -1; }
    tcc_set_error_func(s, 0, tcc_error_cb);
    tcc_set_options(s, "-nostdlib");
    if (tcc_set_output_type(s, TCC_OUTPUT_OBJ) < 0) goto fail;

    for (unsigned i = 0; i < GUEST_SYM_COUNT; i++)
        tcc_add_symbol(s, guest_syms[i].name, guest_syms[i].addr);

    if ((r->source ? tcc_compile_string(s, r->source) : tcc_add_file(s, r->name)) < 0) goto fail;
    if (tcc_output_file(s, r->out_path) < 0) goto fail;

    r->ok = 1;
    tcc_delete(s);
    return 0;
fail:
    tcc_delete(s);
    return -1;
}

#define STACK_WANT (768 * 1024)
#define STACK_MIN  (128 * 1024)

static int on_big_stack(int (*fn)(void *), void *arg) {
    size_t sz = STACK_WANT;
    uint8_t *mem = 0;
    while (sz >= STACK_MIN && !(mem = (uint8_t *)malloc(sz))) sz /= 2;
    if (!mem) { kklog("cc: not enough memory for the compiler stack"); return -1; }
    memset(mem, 0xA5, 64);                            /* overflow canary */

    tcc_os_fpu_init();
    uintptr_t top = ((uintptr_t)mem + sz) & ~(uintptr_t)15;
    int rc = tcc_os_call_on_stack((void *)top, fn, arg);

    for (int i = 0; i < 64; i++)
        if (mem[i] != 0xA5) { kklog("cc: WARNING: compiler stack overflowed (program too big/deep?)"); break; }
    free(mem);
    return rc;
}

int tcc_os_run_file(const char *path, int argc, char **argv, int *exit_code) {
    run_req_t r = { path, 0, argc, argv, 0, 0 };
    int rc = on_big_stack(do_run, &r);
    if (exit_code) *exit_code = r.exit_code;
    return (rc == 0 && r.compiled) ? 0 : -1;
}

int tcc_os_run_source(const char *name, const char *source, int argc, char **argv, int *exit_code) {
    run_req_t r = { name, source, argc, argv, 0, 0 };
    int rc = on_big_stack(do_run, &r);
    if (exit_code) *exit_code = r.exit_code;
    return (rc == 0 && r.compiled) ? 0 : -1;
}

int tcc_os_compile_obj_file(const char *path, const char *out_path) {
    compile_req_t r = { path, 0, out_path, 0 };
    int rc = on_big_stack(do_compile_obj, &r);
    return (rc == 0 && r.ok) ? 0 : -1;
}

int tcc_os_compile_obj_source(const char *name, const char *source, const char *out_path) {
    compile_req_t r = { name, source, out_path, 0 };
    int rc = on_big_stack(do_compile_obj, &r);
    return (rc == 0 && r.ok) ? 0 : -1;
}

/* ----------------------------------------------------------- shell hook */

void cmd_cc(int argc, char **argv) {
    int code = 0;
    if (argc < 2) {
        kklog("usage: cc <file.c> [args...]     compile and run a C file");
        kklog("       cc -e \"<C source>\"        compile and run a snippet");
        kklog("       cc -c <file.c> -o <out.o>  compile to an object file and save it to the drive");
        return;
    }
    if (strcmp(argv[1], "-c") == 0) {
        if (argc < 3) { kklog("cc -c: missing source file"); return; }
        const char *src_path = argv[2];
        const char *out_path = 0;
        for (int i = 3; i < argc - 1; i++)
            if (strcmp(argv[i], "-o") == 0) { out_path = argv[i + 1]; break; }
        if (!out_path) { kklog("cc -c: missing -o <out.o>"); return; }
        if (tcc_os_compile_obj_file(src_path, out_path) == 0)
            klogf("[cc] wrote %s\n", out_path);
        else
            klogf("[cc] failed to compile %s\n", src_path);
        return;
    }
    if (strcmp(argv[1], "-e") == 0) {
        if (argc < 3) { kklog("cc -e: missing source"); return; }
        static char src[1024];
        src[0] = 0;
        for (int i = 2; i < argc; i++) {
            if (i > 2) strncat(src, " ", sizeof src - strlen(src) - 1);
            strncat(src, argv[i], sizeof src - strlen(src) - 1);
        }
        char *av[] = { "<cmdline>", 0 };
        if (tcc_os_run_source("<cmdline>", src, 1, av, &code) == 0)
            klogf("[cc] exit code %d\n", code);
        return;
    }
    if (tcc_os_run_file(argv[1], argc - 1, argv + 1, &code) == 0)
        klogf("[cc] %s exited with code %d\n", argv[1], code);
}